#!/usr/bin/env python3
"""
Auto-generate a demo GIF of the RAGTrace UI using Playwright.
Requires: playwright, Pillow
Usage: python3 ui/make_demo_gif.py
Output: ui/demo.gif
"""

import asyncio
import os
from pathlib import Path
from PIL import Image
from playwright.async_api import async_playwright

UI_URL = "http://localhost:3000"
REPO_ROOT = Path(__file__).parent.parent
OUT_DIR = Path(__file__).parent / "_demo_frames"
OUT_GIF = Path(__file__).parent / "demo.gif"

# Sessions generated by generate_test_data_v2.py
SESSIONS = [
    "5cbfcee5-bab7-4f56-a0ad-bfd619423d65",
    "7794102d-0693-4b08-b956-a772080defa9",
    "3b4eb42d-bfd0-4afd-8183-09a2641784ff",
]


async def shot(page, name: str, frames: list, pause_ms: int = 1200):
    """Take a screenshot and append it to frames (repeated for pause duration)."""
    path = OUT_DIR / f"{name}.png"
    await page.screenshot(path=str(path), full_page=False)
    img = Image.open(path).convert("RGBA")
    # Repeat the frame so it stays visible for pause_ms at 10fps
    repeats = max(1, pause_ms // 100)
    for _ in range(repeats):
        frames.append(img.copy())
    print(f"  ✓ {name}")


async def run():
    OUT_DIR.mkdir(exist_ok=True)
    frames = []

    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        ctx = await browser.new_context(viewport={"width": 1280, "height": 800})
        page = await ctx.new_page()

        print("→ Sessions tab")
        await page.goto(UI_URL, wait_until="networkidle")
        await page.wait_for_timeout(800)
        await shot(page, "01_sessions_empty", frames, 800)

        # Click Sessions nav (it's the default, just making sure)
        await page.click("text=Sessions")
        await page.wait_for_timeout(1000)
        await shot(page, "02_sessions_loaded", frames, 1500)

        # Scroll down in sessions list to show more entries
        await page.keyboard.press("End")
        await page.wait_for_timeout(500)
        await shot(page, "03_sessions_scroll", frames, 800)
        await page.keyboard.press("Home")

        print("→ Sessions — open first session card")
        first_card = page.locator(".session-card").first
        await first_card.wait_for(timeout=5000)
        await first_card.click()
        await page.wait_for_timeout(1500)
        await shot(page, "04_timeline_header", frames, 1200)

        # Scroll down to reveal waterfall + cost chart
        await page.evaluate("window.scrollBy(0, 300)")
        await page.wait_for_timeout(600)
        await shot(page, "05_timeline_charts", frames, 1800)

        # Scroll further to show events timeline
        await page.evaluate("window.scrollBy(0, 400)")
        await page.wait_for_timeout(600)
        await shot(page, "06_timeline_events", frames, 1500)

        # Click first timeline event to show details
        event = page.locator(".timeline-event").first
        if await event.count() > 0:
            await event.click()
            await page.wait_for_timeout(800)
            await shot(page, "07_event_details", frames, 1500)

        print("→ Regression tab")
        await page.goto(UI_URL, wait_until="networkidle")
        await page.wait_for_timeout(500)
        await page.click("text=Regression")
        await page.wait_for_timeout(1000)
        await shot(page, "08_regression_empty", frames, 1000)

        # Open Create Snapshot modal
        create_btn = page.locator("button:has-text('New Snapshot'), button:has-text('Create First Snapshot')")
        if await create_btn.count() > 0:
            await create_btn.first.click()
            await page.wait_for_timeout(1200)
            await shot(page, "09_snapshot_modal_open", frames, 1000)

            # Select a session from dropdown
            select = page.locator("#snapshot-session-id")
            if await select.count() > 0:
                options = await select.locator("option").all()
                if len(options) > 0:
                    await select.select_option(index=0)
                    await page.wait_for_timeout(400)
                    await shot(page, "10_snapshot_session_selected", frames, 1000)

                    # Add a tag
                    await page.fill("#snapshot-tags", "baseline")
                    await page.wait_for_timeout(300)
                    await shot(page, "11_snapshot_tags", frames, 800)

                    # Submit
                    await page.click("button:has-text('Create Snapshot')")
                    await page.wait_for_timeout(1500)
                    await shot(page, "12_snapshot_created", frames, 1500)

            # Create a second snapshot from a different session
            create_btn2 = page.locator("button:has-text('New Snapshot')")
            if await create_btn2.count() > 0:
                await create_btn2.first.click()
                await page.wait_for_timeout(1200)
                select2 = page.locator("#snapshot-session-id")
                if await select2.count() > 0:
                    opts = await select2.locator("option").all()
                    idx = 1 if len(opts) > 1 else 0
                    await select2.select_option(index=idx)
                    await page.fill("#snapshot-tags", "v2")
                    await page.wait_for_timeout(300)
                    await page.click("button:has-text('Create Snapshot')")
                    await page.wait_for_timeout(1500)
                    await shot(page, "13_two_snapshots", frames, 1500)

        print("→ Prompts tab")
        await page.click("text=Prompts")
        await page.wait_for_timeout(1000)
        await shot(page, "14_prompts_tab", frames, 2000)

        # Final — back to Sessions
        await page.click("text=Sessions")
        await page.wait_for_timeout(800)
        await shot(page, "15_sessions_final", frames, 1200)

        await browser.close()

    # Build GIF
    print(f"\n→ Building GIF from {len(frames)} frames…")
    rgb_frames = [f.convert("RGB") for f in frames]
    rgb_frames[0].save(
        OUT_GIF,
        save_all=True,
        append_images=rgb_frames[1:],
        duration=100,   # 100ms per frame = 10fps
        loop=0,
        optimize=True,
    )
    size_kb = OUT_GIF.stat().st_size // 1024
    print(f"✅ Saved: {OUT_GIF}  ({size_kb} KB)")


if __name__ == "__main__":
    asyncio.run(run())
